### ISSUE TITLE
Rhymestone VIA/VIAL definitions do not work

### ISSUE THREAD

**Issue by darknessblade** [marksard/Keyboards#3]
Just as the Title says the VIA/VIAL definitons are outdated, and do not work with the current version of VIA.

the JSON file gives errors, when trying to load/sideload it.

I also have the issue that with the default layout the bottom row does not work

**Comment by darknessblade** [comment]
Update: The bottom row issue seems to be caused by the arduino I used, it had a defective trace/bad connection.

**Comment by darknessblade** [comment]
Is there been any update on adding VIA/VIAL support for the Rhymestone?

**Comment by darknessblade** [comment]
I tried making my own Vial Fork, but for some reason It is not working correctly.
[rhymestone - Vial test.zip](https://github.com/marksard/Keyboards/files/9654144/rhymestone.-.Vial.test.zip)

The firmware itself flashes without problem, but VIAL does not recognize the keyboard.
This might be due it being a Split keyboard with 2 Arduino halves. [I did flash both with the same firmware]

**Comment by darknessblade** [comment]
Found the VIA version on the QMK github page.
for some reason with MSYS it did not download so i had to add the files to the keymap/firmware directory, myself.

The VIA firmware seems to be working fine. though the only Issue I encounter for now is when I try to sideload it into VIAL.
______________
File "main_window.py", line 284, in on_device_selected
  File "main_window.py", line 304, in rebuild
  File "editor\keymap_editor.py", line 125, in rebuild
  File "keycodes.py", line 870, in recreate_keyboard_keycodes

AttributeError: 'Keyboard' object has no attribute 'tap_dance_count'
_____________
Since I now have the VIA_keymap.JSON, I can more easily see if I can make my own VIAL compatible version, that does not have the sideloading issue.

**Comment by darknessblade** [comment]
Build my own VIAL "fork" for the Rhymestone 
https://github.com/darknessblade/Rhymestone_VIAL_firmware

The only Issue I have is that from the RIGHT-side keyboard the OLED does not work. [This is also the case with the VIA firmware]
[Left side works fine]

**Comment by darknessblade** [comment]
there are a few issues with vial. it shows the RGB menu even with RGB disabled. not sure what causes this issue, gonna test a few things later to see if I can fix this,

havent found any other issues yet

**Comment by marksard** [comment]
Sorry I didn't notice.
Please use the file here.
We have confirmed that it works with REMAP.
https://github.com/marksard/qmk_firmware_hex/releases
https://remap-keys.app/

Sorry about the vial support, we cannot respond.
